mod bottom_panel;
mod buttons;
mod clip;
mod effect;
mod effects;
mod filebrowser;
mod grid;
mod left_panel;
mod loudness_meter;
mod top_bar;
mod track;
mod track_manager;
mod waveform;
pub(crate) mod workspace;
